name: Test
on: [pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install Roc
        uses: hasnep/setup-roc@main
        with:
          roc-version: nightly

      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0

      - name: Build platform
        run: zig build -Doptimize=ReleaseFast

      - name: Run example
        run: roc examples/day.roc
